language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

install:
  - python -c "import os;print os.environ"
  - git --git-dir=${TRAVIS_BUILD_DIR}/.git fetch origin ${TRAVIS_BRANCH} && git --git-dir=${TRAVIS_BUILD_DIR}/.git diff --name-only ${TRAVIS_BRANCH}.. >${TRAVIS_BUILD_DIR}/diff-name-only.diff
  - cat ${TRAVIS_BUILD_DIR}/diff.diff
  - python -c "print ','.join( list( set( [fname_diff.split('/')[0] for fname_diff in open('${TRAVIS_BUILD_DIR}/diff-name-only.diff', 'r').read().strip('\n').split('\n')] ) ))"

script:
  - exit(0)
