language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

install:
  - python -c "import os;print os.environ"
  - ls -la ${TRAVIS_BUILD_DIR}
  # - tree -a ${TRAVIS_BUILD_DIR}
  - git --git-dir=${TRAVIS_BUILD_DIR}/.git branch -a
  - git --git-dir=${TRAVIS_BUILD_DIR}/.git remote -v

script:
  - exit(0)
