language: python

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility

virtualenv:
  system_site_packages: true

script:
  - echo "normal color" && python ${TRAVIS_BUILD_DIR}/logging_test.py
  - echo "travis_wait color" && travis_wait python ${TRAVIS_BUILD_DIR}/logging_test.py
  - echo "travis_wait unbuffer color" && travis_wait unbuffer python ${TRAVIS_BUILD_DIR}/logging_test.py

