language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

script:
  - python ${TRAVIS_BUILD_DIR}/logging_test.py
  - travis_wait python ${TRAVIS_BUILD_DIR}/logging_test.py

  - python ${TRAVIS_BUILD_DIR}/subprocess_call_test.py
  - travis_wait python ${TRAVIS_BUILD_DIR}/subprocess_call_test.py

