language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

install:
  - git --git-dir=${TRAVIS_BUILD_DIR}/.git fetch origin ${TRAVIS_BRANCH} && git --git-dir=${TRAVIS_BUILD_DIR}/.git diff --name-only ${TRAVIS_BRANCH}.. >${TRAVIS_BUILD_DIR}/diff-name-only.diff
  - cat ${TRAVIS_BUILD_DIR}/diff-name-only.diff
  - python -c "print 'export INCLUDE=\"' + ' '.join( list( set( [fname_diff.split('/')[0] for fname_diff in open('${TRAVIS_BUILD_DIR}/diff-name-only.diff', 'r').read().strip('\n').split('\n') if '/' in fname_diff] ) )) + '\"'" >${TRAVIS_BUILD_DIR}/modules.profile
  - cat ${TRAVIS_BUILD_DIR}/modules.profile
  - source ${TRAVIS_BUILD_DIR}/modules.profile
  - echo ${INCLUDE}
  - sudo pip install pylint flake8
  - curl https://raw.githubusercontent.com/Vauxoo/pylint-conf/master/conf/pylint_vauxoo_light.cfg -o ${HOME}/.pylint.conf
  - curl https://raw.githubusercontent.com/Vauxoo/maintainer-quality-tools/master/travis/cfg/travis_run_flake8__init__.cfg -o ${HOME}/.flake8__init__.cfg
  - curl https://raw.githubusercontent.com/Vauxoo/maintainer-quality-tools/master/travis/cfg/travis_run_flake8.cfg -o ${HOME}/.flake8.cfg

script:
  - pylint --rcfile=${HOME}/.pylint.conf ${INCLUDE}
  - flake8 --config=${HOME}/.flake8__init__.cfg ${INCLUDE}
  - flake8 --config=${HOME}/.flake8.cfg ${INCLUDE}